var i = 0; var j = 0; var printyr = "";
var colorpallete = ["primary", "warning", "danger", "success"];
var targetuser = ["Daksh Tak", "Isha Ranka", "Riya Singh Gehlot", "Sparsh Singhal", "Ishan Mathur", "Maitrayee Arya", "Prasoon Raj", "Faraz Ahmed"];
var useriamge = ["daksh", "isha", "riya", "sparsh", "ishan", "maitrayee", "prasoon", "faraz"];
var aboutuser = ["Daksh Tak hails from the esteemed CEPT university of India. Pursuing the distinguished course of “Urban Design”. He has completed his schooling from St Anslem’s School, Ajmer, Rajasthan, India, graduating as the winning Captain of the Rabindranath Tagore House. Being an artist, he has his keen interests vested in the initiative of youth empowerment through the medium of Design and its perspectives. What sets him apart are the assets of dedication and hard work he brings along with him. Throughout his tenure at your benevolent organization. Having his roots in Design since the inception of his school days, Daksh always keeps himself inspired and motivated, never failing to bring something novel and unique to the table. One such of his novelties include his company “Hackney” and its respective branches. Among various creative inputs, the list includes the organization of Ishara through which he wants to empower art and artists of his own city, Ajmer.",
                "Isha Ranka is a soul writer and has various roots to art and performing arts. She belongs to the Community of Sophia School Amer, Rajasthan and has been a charming person and an admirer of art and its branches. She has subjective interests towards English Literature, Political Science and Human Psychology. Her later interest lies in Interior and Space design from Rachna Sansadh School of Interior Design, Mumbai, India. Being the Co-founder of Ishara her vision coveys an aim of creating a vast community that would bring all art forms and artists under an umbrella and encourage them to reach out to public and express themselves freely. She believes that participation than achieving something",
                "Riya Singh Gehlot, currently is Manipal University Jaipur getting gravitas of Automobile Engineering. She has worked with Ford Motors and Maruti Suzuki for various social and privates projects which marks her key interests. She has completed her schooling from Sophia School Ajmer, graduating as Head Girl of the school for 2015-16. Riya has brought many Loyal in art and one among them is Internationally recognized Sankar Art Award in Oil Painting. Her vision with Ishara speaks about bringing up art to eye level of society and community of Ajmer itself. She believes that preserving art and art forms is a need of hour as its uniqueness and perspectives are at the level of extinctions, expansions and upliftment of artist’s community through various means is a necessity.",
                "Sparsh Singhal is a music producer/DJ based in Ajmer, Rajasthan, supported by a bunch of other artists including Ehsaan Noorani, David Guetta, Alesso and many more. He’s a pianist and has been playing the piano for almost fourteen years now. Currently, he’s studying at St. Stephen’s School, Ajmer and he is an Editor and Writer of his school magazine named ‘Stephenia’ has been involved in various activities in performing arts. As an artist himself he believes that the lack of public support is killing many artists from within and forcing them to quit. It is very important for people to understand and save art forms and the artists. To keep them growing a sense of encouragement and support form the public. His vision is to build a community for all the underground artists who lack public support and social exposure. For them to come out from their comfort zones and bring them to discomfort",
                "Ishan Mathur started his education from St. Anselm's Sr. Sec. School. He was always keen and fascinated about how technology works. Now he is obsessed with his lifestyle which revolves around Tech Companies and Programming. Tackling the back-end is at his core heart. Learning is the biggest part of his life. Also he shares an interest and value in stock market and is up to date with latest news. Helping people better understand art behind programming and how stock market works is what he would like to do in future. Ishara in many ways is helping him build more interest in Art & Design and learn how to tackle initial problems in business. Also working on website for Ishara sharpens his Skills",
                "Maitrayee Arya , is from Ajmer and has completed her schooling from Sophia senior secondary school Ajmer. She works as an Production design Assistant and also a freelance stylist. She has been into Film making from the past two years and have worked in several TV advertisements, Feature Films and Web series like Made In Heaven , Laakhon Me Ek, Dolly Kitty and many more. She has completed her Graduation from Asian School of Media Studies, Noida with a degree of B.SC in Cinema and Film Making. Maitrayee thinks that’s Creativity takes courage and so with her courage and creativity she landed into the beautiful form of art which is Films. She feels when she looks at life though camera she can actually feel it and this creative urge in her bought her to Ishara. Back when she was in school she never had such an opportunity or medium to express her form of Art and now when she has the resources and capability to make people experience this why wouldn’t she. Ishara for her is a medium to boost up the youth of Ajmer towards awareness of art.",
                "Prasoon Raj Singh Rathore, also called just Prasoon for convenience, is not someone new to the city. He has been seen over the years as someone who’s actively participating and organising various events in Ajmer. Graduating from Mayoor School Ajmer last year as the head boy he has taken new routes and has went on to double major in Physics and Economics from University of Wisconsin-Madison in the United States. Having returned back home after the end of his freshmen year, he wants to put his time and effort to the best of its use by being a helping hand for Ishara. He believes that the platform will help budding artists to bloom to their maximum and will introduce the city of Ajmer to the beautiful world of art which it has been deprived of for so long",
                "Faraz Ahmed, is currently in National Institute of Fashion Technology, Jodhpur pursuing Fashion Communication. Born and brought up in Ajmer, belongs to the community of St. Anselms. Photography and art are his one amongst keen interests and is known for his amazing photoshoots and artistic skills. He is the co founder of “Hackney”. His vision with Ishara is to give a platform for children and youngsters in-discriminative of their background. He believes that art has no boundaries and discriminative perspectives towards the artists. Social and communal acceptance of artists works as a support system and source of encouragement to produce more work. The idea of Ishara as a community and art preservations working with a school of art has his support and is the key reason for him to belong to this community."]
for (i = 0, j = 0; i < 8; i++, j++) {
    printyr +=
        '<div class="card" style="margin: 10px; padding: 10px; border-radius: 10px;">' +
            '<img src="../img/team/' + useriamge[i] + '.png" width="150px" alt="...">' +
            '<div class="card-body">' +
                '<h5 class="card-title">' + targetuser[i] + '</h5>' +
            '</div>' +
        '</div>'; 
    
    document.getElementById("showteam").innerHTML = printyr;
}        